version: "3.5"

networks:
  localdev:
    name: localdev

services:
  main-api:
    build: .
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db-server
    networks:
      - localdev
  db-server:
    container_name: db
    image: mysql:8.0.18
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_HOST: localhost
      MYSQL_DATABASE: shelter
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "1433:1433"
    networks:
      - localdev
