version: "3.5"

networks:
  localdev:
    name: localdev

services:
  main-api:
    build: .
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db-server
    networks:
      - localdev

  db-server:
    container_name: db-server
    image: mysql:5.7
    environment:
      - "MYSQL_DATABASE=shelter"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=root"
      - "MYSQL_ROOT_PASSWORD=root"
    ports:
      - "1400:1433"
    networks:
      - localdev
