version: "3.5"

networks:
  localdev:
    name: localdev

services:
  main-api:
    container_name: main-api
    build: .
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db-server
    volumes:
      - appbuild:/app
    links:
      - db-server
    networks:
      - localdev

  db-server:
    container_name: db-server
    image: mysql:8.0.18
    restart: always
    volumes:
      - dbvol:/var/lib/mysql
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_HOST: localhost
      MYSQL_DATABASE: shelter
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - localdev

volumes:
  appbuild:
  dbvol:
